name: Deploy to VPS  # nazwa workflowa

on:
  push:               # co go uruchamia?
    branches:
      - main          # działa tylko po puszu na gałąź "main"

jobs:
  deploy:             # nazwa zadania (może być dowolna)
    runs-on: ubuntu-latest  # GitHub odpali to na maszynie z Ubuntu

    steps:            # lista kroków do wykonania
      - name: Connect to VPS and pull latest code
        uses: appleboy/ssh-action@v1.0.0  # gotowa akcja do łączenia przez SSH
        with:
          host: ${{ VPS_HOST }}       # IP Twojego serwera
          username: ${{ VPS_USER }}   # użytkownik na VPS (np. "ubuntu")
          key: ${{ VPS_SSH_KEY  }}         # klucz prywatny SSH
          script: |                            # komendy, które wykona na VPS
            cd /var/www/mysite/aboutme
            git pull origin main
